# Generated by Django 5.0 on 2023-12-10 14:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0002_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='auth_user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='QuizQandA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_id', models.CharField(max_length=30)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsd_main_app.question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(max_length=40)),
                ('dp_level', models.CharField(max_length=100)),
                ('no_of_days', models.CharField(max_length=20)),
                ('conclusion', models.CharField(max_length=200)),
                ('counselor_or_not', models.CharField(max_length=1)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('questions', models.ManyToManyField(through='tsd_main_app.QuizQandA', to='tsd_main_app.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsd_main_app.user')),
            ],
        ),
        migrations.AddField(
            model_name='quizqanda',
            name='quiz_result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tsd_main_app.quizresult'),
        ),
    ]
