# Generated by Django 5.0 on 2024-01-26 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0002_admin_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='message',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
