# Generated by Django 5.0 on 2023-12-28 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0005_rolepage_fe_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rolepage',
            name='fe_route',
        ),
        migrations.AddField(
            model_name='page',
            name='fe_route',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
