# Generated by Django 5.0 on 2023-12-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0006_remove_rolepage_fe_route_page_fe_route'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='email',
        ),
    ]
