# Generated by Django 5.0 on 2024-06-20 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0006_privatequestions_is_patient_viewed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolepage',
            old_name='create',
            new_name='can_create',
        ),
        migrations.RenameField(
            model_name='rolepage',
            old_name='delete',
            new_name='can_delete',
        ),
        migrations.RenameField(
            model_name='rolepage',
            old_name='read',
            new_name='can_read',
        ),
        migrations.RenameField(
            model_name='rolepage',
            old_name='update',
            new_name='can_update',
        ),
    ]
