# Generated by Django 5.0 on 2024-06-28 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0007_rename_create_rolepage_can_create_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authuser',
            name='otp',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='authuser',
            name='otp_expires_at',
            field=models.DateTimeField(null=True),
        ),
    ]
