# Generated by Django 5.0 on 2023-12-29 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0008_admindetails_delete_admin'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AdminDetails',
            new_name='Admin',
        ),
    ]
