# Generated by Django 5.0 on 2023-12-30 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0010_appointment_admin_quiz_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='accepted',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
