# Generated by Django 5.0 on 2024-01-01 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tsd_main_app', '0012_question_is_updating_question_last_updated_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='accepted',
            new_name='is_checked',
        ),
    ]
